// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pane': string;
  'pane-group': string;
  'pane-mini': string;
  'pane-one-fourth': string;
  'pane-one-third': string;
  'pane-sm': string;
}
export const cssExports: CssExports;
export default cssExports;
