// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btn-group': string;
  'title': string;
  'toolbar': string;
  'toolbar-actions': string;
  'toolbar-borderless': string;
  'toolbar-header': string;
}
export const cssExports: CssExports;
export default cssExports;
