// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'window': string;
  'window-content': string;
}
export const cssExports: CssExports;
export default cssExports;
