import Head from 'next/head'
import { useEffect } from 'react'
import Image from 'next/image'
import { Button, Radio, Space, Divider } from 'antd';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { invoke } from '@tauri-apps/api/tauri'
import React, { useState } from 'react';
import type { SizeType } from 'antd/es/config-provider/SizeContext';

const inter = Inter({ subsets: ['latin'] })
const isClient = typeof window !== 'undefined'

export default function Home() {
  const [size, setSize] = useState<SizeType>('large');
  useEffect(() => {
    invoke('greet', { name: 'World' })
    .then(console.log)
    .catch(console.error)
  }, []);
  return (
    <>
      <Head>
        <title>CreateApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Radio.Group value={size} onChange={(e) => setSize(e.target.value)}>
        <Radio.Button value="large">Large</Radio.Button>
        <Radio.Button value="default">Default</Radio.Button>
        <Radio.Button value="small">Small</Radio.Button>
      </Radio.Group>
        <div className={styles.center}>
          
        </div>

        <div className={styles.grid}>


        </div>
      </main>
    </>
  )
}
